#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/annik/neuron/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/annik/neuron/nrn/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/annik/Dropbox/msc/SciNet/2017/SCM/x86_64/.libs/libnrnmech.so" "$@"
